## Numpy

In [1]:
import numpy as np


In [2]:
a = [2,4, 6, 8, 10]
x = np.array(a)

In [3]:
print(x)
print(x.shape)
print(x.ndim)

[ 2  4  6  8 10]
(5,)
1


In [4]:
b = np.array([[2, 3, 4], [6, 2, 1]])

print(b.shape)
print(b.ndim)

(2, 3)
2


In [5]:
print(b)

[[2 3 4]
 [6 2 1]]


In [9]:
np.random.random((2,2))

array([[0.35594348, 0.70266368],
       [0.22648714, 0.96240439]])

In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [11]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

## Pandas

In [16]:
import pandas as pd

In [19]:
days = pd.Series(['Monday', 'Tuesday', 'Wednesday'], index=['day1', 'day2', 'day3'])
days_2 = pd.Series({'day1':'Monday', 'day2':'Tuesday', 'days3':'Wednesday'})

In [18]:
days

day1       Monday
day2      Tuesday
day3    Wednesday
dtype: object

In [20]:
days_2

day1        Monday
day2       Tuesday
days3    Wednesday
dtype: object

In [21]:
df_dict = {'Country':['Nigeria', 'Togo'], 'Population':[2300000, 566666], 'Age':[57, 36]}
df = pd.DataFrame(df_dict, index=[3, 5])
df

Country  Population  Age
3  Nigeria     2300000   57
5     Togo      566666   36

In [23]:
df.iloc[0]

Country       Nigeria
Population    2300000
Age                57
Name: 3, dtype: object

In [24]:
df['Country']

3    Nigeria
5       Togo
Name: Country, dtype: object

In [27]:
df.at[5, 'Age'] # [index, column_label]

36

In [28]:
df.iat[1, 2]

36